import { StyleSheet } from 'react-native';

import { colors, typography } from '../../../../Theme';

const styles = StyleSheet.create({
  addLimitCategoryButton: {
    alignItems: 'center',
    alignSelf: 'stretch',
    backgroundColor: 'rgba(255, 204, 213, 0.08)',
    borderColor: 'rgba(238, 43, 108, 0.22)',
    borderRadius: 24,
    borderStyle: 'dashed',
    borderWidth: 2,
    justifyContent: 'center',
    marginTop: 6,
    paddingHorizontal: 18,
    paddingVertical: 20,
  },
  addLimitCategoryText: {
    color: colors.primary,
    fontFamily: typography.fontFamily,
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
  },
  blueLimitProgress: {
    backgroundColor: colors.secondary,
  },
  blueLimitText: {
    color: colors.secondary,
  },
  categoryPresetRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  colorSwatch: {
    borderColor: colors.white,
    borderRadius: 16,
    borderWidth: 3,
    height: 32,
    width: 32,
  },
  colorSwatchActive: {
    shadowColor: colors.slate900,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 8,
  },
  iconPresetChip: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 204, 213, 0.12)',
    borderColor: 'rgba(255, 204, 213, 0.28)',
    borderRadius: 18,
    borderWidth: 1,
    height: 76,
    justifyContent: 'center',
    width: 76,
  },
  iconPresetChipActive: {
    backgroundColor: 'rgba(238, 43, 108, 0.12)',
    borderColor: colors.primary,
  },
  iconPresetSymbol: {
    color: colors.slate900,
    fontSize: 28,
    fontWeight: '800',
  },
  limitAmount: {
    color: colors.slate600,
    fontFamily: typography.fontFamily,
    fontSize: 20,
    fontWeight: '500',
    marginTop: 18,
    textAlign: 'right',
  },
  limitAmountUsed: {
    color: colors.slate900,
    fontWeight: '800',
  },
  limitBadge: {
    backgroundColor: 'rgba(255, 204, 213, 0.45)',
    borderRadius: 18,
    color: colors.primary,
    flexShrink: 0,
    fontFamily: typography.fontFamily,
    fontSize: 14,
    fontWeight: '800',
    minWidth: 56,
    paddingHorizontal: 12,
    paddingVertical: 7,
    textAlign: 'center',
  },
  limitCard: {
    backgroundColor: colors.white,
    borderColor: 'rgba(238, 43, 108, 0.08)',
    borderRadius: 24,
    borderWidth: 1,
    padding: 22,
    shadowColor: colors.primary,
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
  },
  limitDetailContainer: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    paddingBottom: 42,
    paddingHorizontal: 24,
    paddingTop: 14,
    width: '100%',
  },
  limitDetailContent: {
    gap: 24,
  },
  limitDetailHandle: {
    alignSelf: 'center',
    backgroundColor: '#DDE3EC',
    borderRadius: 4,
    height: 8,
    marginBottom: 24,
    width: 56,
  },
  limitDetailHeader: {
    marginBottom: 30,
  },
  limitDetailIcon: {
    fontSize: 24,
    fontWeight: '800',
    width: 30,
  },
  limitDetailItem: {
    gap: 10,
    position: 'relative',
  },
  limitDetailItemHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  limitDetailItemLeft: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  limitDetailItemRight: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  limitDetailLabel: {
    color: colors.slate600,
    fontFamily: typography.fontFamily,
    fontSize: 15,
    fontWeight: '800',
  },
  limitDetailPercent: {
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  limitDetailProgress: {
    borderRadius: 5,
    height: '100%',
  },
  limitDetailSubtitle: {
    color: colors.primary,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1,
  },
  limitDetailTitle: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 6,
  },
  limitDetailTitleCopy: {
    flex: 1,
    minWidth: 0,
  },
  limitDetailTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'space-between',
  },
  limitDetailTrack: {
    backgroundColor: '#F1F5F9',
    borderRadius: 5,
    height: 10,
    overflow: 'hidden',
  },
  limitEmptyState: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 204, 213, 0.1)',
    borderColor: 'rgba(238, 43, 108, 0.14)',
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    paddingHorizontal: 18,
    paddingVertical: 30,
  },
  limitEmptyText: {
    color: colors.slate400,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
    maxWidth: 230,
    textAlign: 'center',
  },
  limitEmptyTitle: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 17,
    fontWeight: '800',
  },
  limitFormLoadingState: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 160,
    paddingVertical: 16,
  },
  limitHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  limitHeaderAction: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  limitIcon: {
    color: colors.primary,
    fontSize: 26,
    fontWeight: '800',
  },
  limitLoadingSheetState: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 260,
    paddingVertical: 24,
  },
  limitLoadingSpinner: {
    color: colors.primary,
  },
  limitLoadingState: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 144,
  },
  limitLoadingText: {
    color: colors.slate400,
    fontFamily: typography.fontFamily,
    fontSize: 13,
    fontWeight: '800',
    marginTop: 12,
    textAlign: 'center',
  },
  limitProgress: {
    backgroundColor: colors.primary,
    borderRadius: 7,
    height: '100%',
    width: '60%',
  },
  limitSecondaryButton: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderColor: 'rgba(238, 43, 108, 0.24)',
    borderRadius: 18,
    borderWidth: 1,
    marginTop: -4,
    paddingVertical: 16,
  },
  limitSecondaryButtonText: {
    color: colors.primary,
    fontFamily: typography.fontFamily,
    fontSize: 14,
    fontWeight: '800',
  },
  limitSection: {
    marginTop: 28,
    paddingHorizontal: 24,
  },
  limitTitle: {
    color: colors.slate900,
    flexShrink: 1,
    fontFamily: typography.fontFamily,
    fontSize: 20,
    fontWeight: '800',
  },
  limitTitleRow: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 12,
    minWidth: 0,
  },
  limitTrack: {
    backgroundColor: '#EDF2F7',
    borderRadius: 8,
    height: 14,
    overflow: 'hidden',
    width: '100%',
  },
  primaryLimitProgress: {
    backgroundColor: colors.primary,
  },
  primaryLimitText: {
    color: colors.primary,
  },
  purpleLimitProgress: {
    backgroundColor: '#A855F7',
  },
  purpleLimitText: {
    color: '#A855F7',
  },
  saveWalletButton: {
    alignItems: 'center',
    backgroundColor: colors.slate900,
    borderRadius: 18,
    marginTop: 10,
    paddingVertical: 18,
    shadowColor: colors.slate900,
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
  },
  saveWalletButtonText: {
    color: colors.white,
    fontFamily: typography.fontFamily,
    fontSize: 15,
    fontWeight: '800',
  },
  sheetBackButton: {
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    marginRight: 12,
    width: 36,
  },
  sheetBackText: {
    color: colors.slate600,
    fontSize: 30,
    fontWeight: '800',
    lineHeight: 32,
  },
  sheetCloseButton: {
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  sheetCloseText: {
    color: colors.slate400,
    fontSize: 26,
    lineHeight: 28,
  },
  sheetHandle: {
    alignSelf: 'center',
    backgroundColor: colors.accentPink,
    borderRadius: 4,
    height: 8,
    marginBottom: 24,
    width: 72,
  },
  sheetHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  sheetTitle: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 22,
    fontWeight: '800',
  },
  sheetTitleArea: {
    flex: 1,
  },
  usePreviousLimitButton: {
    alignItems: 'center',
    backgroundColor: colors.slate900,
    borderRadius: 18,
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    width: '100%',
  },
  usePreviousLimitText: {
    color: colors.white,
    fontFamily: typography.fontFamily,
    fontSize: 14,
    fontWeight: '800',
  },
  walletDeleteButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderColor: colors.white,
    borderRadius: 14,
    borderWidth: 2,
    height: 28,
    justifyContent: 'center',
    position: 'absolute',
    right: 10,
    top: 10,
    width: 28,
    zIndex: 2,
  },
  walletDeleteText: {
    color: colors.white,
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 22,
  },
  walletEditButton: {
    alignItems: 'center',
    backgroundColor: colors.secondary,
    borderColor: colors.white,
    borderRadius: 14,
    borderWidth: 2,
    height: 28,
    justifyContent: 'center',
    position: 'absolute',
    right: 10,
    top: 10,
    width: 28,
    zIndex: 2,
  },
  walletEditText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 16,
  },
  walletForm: {
    gap: 18,
  },
  walletFormField: {
    gap: 8,
  },
  walletFormInput: {
    backgroundColor: 'rgba(255, 204, 213, 0.16)',
    borderColor: 'rgba(255, 204, 213, 0.34)',
    borderRadius: 18,
    borderWidth: 1,
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 15,
    fontWeight: '700',
    minHeight: 60,
    paddingHorizontal: 18,
  },
  walletFormLabel: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
    marginLeft: 8,
  },
  walletTrashButton: {
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    marginRight: 10,
    width: 36,
  },
  walletTrashButtonActive: {
    backgroundColor: 'rgba(238, 43, 108, 0.14)',
  },
  walletTrashButtonDisabled: {
    opacity: 0.38,
  },
  walletTrashText: {
    fontSize: 18,
    lineHeight: 21,
  },
  walletTypeChip: {
    backgroundColor: 'rgba(255, 204, 213, 0.14)',
    borderColor: 'rgba(255, 204, 213, 0.32)',
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  walletTypeChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  walletTypeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  walletTypeText: {
    color: colors.slate600,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  walletTypeTextActive: {
    color: colors.white,
  },
  yellowLimitProgress: {
    backgroundColor: colors.tertiary,
  },
  yellowLimitText: {
    color: '#CA8A04',
  },
});

export default styles;
