import { StyleSheet } from 'react-native';

import { colors, typography } from '../../Theme';

const styles = StyleSheet.create({
  avatar: {
    alignItems: 'center',
    backgroundColor: colors.accentPink,
    borderColor: 'rgba(238, 43, 108, 0.2)',
    borderRadius: 26,
    borderWidth: 2,
    height: 52,
    justifyContent: 'center',
    width: 52,
  },
  avatarText: {
    color: colors.primary,
    fontSize: 26,
    fontWeight: '800',
  },
  blueWalletAmount: {
    color: colors.secondary,
  },
  blueWalletIcon: {
    backgroundColor: colors.secondary,
  },
  blueWalletOption: {
    backgroundColor: 'rgba(202, 240, 248, 0.55)',
    borderColor: 'rgba(78, 168, 222, 0.16)',
  },
  balanceBadge: {
    backgroundColor: 'rgba(255, 255, 255, 0.24)',
    borderColor: 'rgba(255, 255, 255, 0.22)',
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  balanceBadgeText: {
    color: colors.white,
    fontFamily: typography.fontFamily,
    fontSize: 10,
    fontWeight: '800',
  },
  balanceCard: {
    backgroundColor: colors.primary,
    borderRadius: 22,
    marginHorizontal: 24,
    marginTop: 22,
    overflow: 'hidden',
    padding: 22,
    shadowColor: colors.primary,
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.24,
    shadowRadius: 18,
  },
  balanceHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  balanceLabel: {
    color: colors.white,
    fontFamily: typography.fontFamily,
    fontSize: 14,
    fontWeight: '800',
    opacity: 0.94,
  },
  balanceNote: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    borderRadius: 18,
    color: colors.white,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 14,
    paddingHorizontal: 16,
    paddingVertical: 7,
  },
  balancePattern: {
    bottom: -20,
    color: colors.white,
    fontSize: 180,
    opacity: 0.06,
    position: 'absolute',
    right: -18,
  },
  balanceValue: {
    color: colors.white,
    fontFamily: typography.fontFamily,
    fontSize: 34,
    fontWeight: '800',
  },
  categoryDot: {
    borderRadius: 6,
    height: 12,
    width: 12,
  },
  categoryItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  categoryLabel: {
    color: colors.slate600,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '600',
  },
  categoryList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    justifyContent: 'space-between',
    width: '100%',
  },
  confirmButton: {
    alignItems: 'center',
    backgroundColor: colors.slate900,
    borderRadius: 18,
    marginTop: 28,
    paddingVertical: 18,
    shadowColor: colors.slate900,
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
  },
  confirmButtonText: {
    color: colors.white,
    fontFamily: typography.fontFamily,
    fontSize: 15,
    fontWeight: '800',
  },
  chartArcBase: {
    borderRadius: 86,
    height: 172,
    position: 'absolute',
    width: 172,
  },
  chartCard: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderColor: 'rgba(238, 43, 108, 0.05)',
    borderRadius: 22,
    borderWidth: 1,
    padding: 24,
    shadowColor: colors.slate900,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
  },
  chartCenter: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 54,
    height: 108,
    justifyContent: 'center',
    position: 'absolute',
    width: 108,
  },
  chartCenterLabel: {
    color: colors.slate400,
    fontFamily: typography.fontFamily,
    fontSize: 10,
    fontWeight: '800',
  },
  chartCenterValue: {
    color: colors.primary,
    fontFamily: typography.fontFamily,
    fontSize: 20,
    fontWeight: '800',
  },
  chartRing: {
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 86,
    height: 172,
    justifyContent: 'center',
    marginBottom: 24,
    overflow: 'hidden',
    width: 172,
  },
  container: {
    backgroundColor: colors.backgroundLight,
    flex: 1,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 8,
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  headerIntro: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  hello: {
    color: colors.primary,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.8,
  },
  historyAmountExpense: {
    color: colors.primary,
  },
  historyAmountIncome: {
    color: colors.secondary,
  },
  historyIcon: {
    fontSize: 22,
  },
  historyIconBox: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 204, 213, 0.45)',
    borderRadius: 16,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  historyItem: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 24,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 74,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  historyList: {
    gap: 12,
  },
  historyLeft: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  historyMeta: {
    color: colors.slate400,
    fontFamily: typography.fontFamily,
    fontSize: 10,
    fontWeight: '500',
  },
  historyTitle: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 14,
    fontWeight: '800',
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderColor: 'rgba(238, 43, 108, 0.1)',
    borderRadius: 16,
    borderWidth: 1,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  iconButtonDot: {
    backgroundColor: colors.primary,
    borderColor: colors.white,
    borderRadius: 4,
    borderWidth: 1,
    height: 8,
    position: 'absolute',
    right: 11,
    top: 11,
    width: 8,
  },
  iconButtonText: {
    color: colors.primary,
    fontSize: 22,
  },
  floatingAddButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderColor: colors.backgroundLight,
    borderRadius: 34,
    borderWidth: 4,
    bottom: 22,
    height: 68,
    justifyContent: 'center',
    position: 'absolute',
    right: 24,
    shadowColor: colors.primary,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.36,
    shadowRadius: 14,
    width: 68,
  },
  floatingAddText: {
    color: colors.white,
    fontSize: 38,
    lineHeight: 42,
  },
  fullHistoryAmount: {
    fontFamily: typography.fontFamily,
    fontSize: 18,
    fontWeight: '800',
  },
  fullHistoryAmountExpense: {
    color: colors.slate900,
  },
  fullHistoryAmountIncome: {
    color: colors.accentPurple,
  },
  fullHistoryChip: {
    backgroundColor: colors.white,
    borderColor: 'rgba(255, 204, 213, 0.24)',
    borderRadius: 22,
    borderWidth: 1,
    paddingHorizontal: 22,
    paddingVertical: 12,
    shadowColor: colors.slate900,
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 5,
  },
  fullHistoryChipActive: {
    backgroundColor: colors.slate900,
    borderColor: colors.slate900,
  },
  fullHistoryChipRow: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 24,
  },
  fullHistoryChipText: {
    color: colors.slate600,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  fullHistoryChipTextActive: {
    color: colors.white,
  },
  fullHistoryContainer: {
    backgroundColor: colors.backgroundLight,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    maxHeight: '88%',
    overflow: 'hidden',
    width: '100%',
  },
  fullHistoryContent: {
    gap: 28,
    paddingBottom: 36,
    paddingHorizontal: 0,
    paddingTop: 22,
  },
  fullHistoryGroup: {
    gap: 12,
  },
  fullHistoryGroupTitle: {
    color: colors.slate400,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.2,
    paddingHorizontal: 24,
    textTransform: 'uppercase',
  },
  fullHistoryHandle: {
    alignSelf: 'center',
    backgroundColor: '#DDE3EC',
    borderRadius: 4,
    height: 8,
    marginBottom: 22,
    width: 56,
  },
  fullHistoryHeader: {
    backgroundColor: 'rgba(255, 255, 255, 0.66)',
    borderBottomColor: 'rgba(255, 204, 213, 0.18)',
    borderBottomWidth: 1,
    paddingBottom: 16,
    paddingTop: 14,
  },
  fullHistoryIcon: {
    color: colors.primary,
    fontSize: 22,
    fontWeight: '800',
  },
  fullHistoryIconBox: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 204, 213, 0.28)',
    borderRadius: 20,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  fullHistoryItem: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderColor: 'rgba(238, 43, 108, 0.05)',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 24,
    minHeight: 90,
    padding: 16,
    shadowColor: colors.slate900,
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
  },
  fullHistoryItemCopy: {
    flex: 1,
    minWidth: 0,
  },
  fullHistoryItemIcon: {
    color: colors.primary,
    fontSize: 24,
    fontWeight: '800',
  },
  fullHistoryItemIconBox: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 204, 213, 0.32)',
    borderRadius: 28,
    height: 56,
    justifyContent: 'center',
    width: 56,
  },
  fullHistoryItemLeft: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 14,
    minWidth: 0,
  },
  fullHistoryItemMeta: {
    color: colors.slate400,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
  },
  fullHistoryItemTitle: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 16,
    fontWeight: '800',
  },
  fullHistoryList: {
    gap: 12,
  },
  fullHistoryMonth: {
    backgroundColor: colors.white,
    borderColor: 'rgba(255, 204, 213, 0.22)',
    borderRadius: 18,
    borderWidth: 1,
    color: colors.slate600,
    fontFamily: typography.fontFamily,
    fontSize: 13,
    fontWeight: '800',
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  fullHistoryTitle: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 24,
    fontWeight: '800',
  },
  fullHistoryTitleLeft: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 14,
  },
  fullHistoryTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    marginBottom: 22,
    paddingHorizontal: 24,
  },
  limitAmount: {
    color: colors.slate600,
    fontFamily: typography.fontFamily,
    fontSize: 20,
    fontWeight: '500',
    marginTop: 18,
    textAlign: 'right',
  },
  limitAmountUsed: {
    color: colors.slate900,
    fontWeight: '800',
  },
  limitBadge: {
    backgroundColor: 'rgba(255, 204, 213, 0.45)',
    borderRadius: 18,
    color: colors.primary,
    fontFamily: typography.fontFamily,
    fontSize: 14,
    fontWeight: '800',
    flexShrink: 0,
    minWidth: 56,
    paddingHorizontal: 12,
    paddingVertical: 7,
    textAlign: 'center',
  },
  limitCard: {
    backgroundColor: colors.white,
    borderColor: 'rgba(238, 43, 108, 0.08)',
    borderRadius: 24,
    borderWidth: 1,
    padding: 22,
    shadowColor: colors.primary,
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
  },
  limitHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  limitIcon: {
    color: colors.primary,
    fontSize: 26,
    fontWeight: '800',
  },
  limitProgress: {
    backgroundColor: colors.primary,
    borderRadius: 7,
    height: '100%',
    width: '60%',
  },
  limitSection: {
    marginTop: 28,
    paddingHorizontal: 24,
  },
  limitTitle: {
    color: colors.slate900,
    flexShrink: 1,
    fontFamily: typography.fontFamily,
    fontSize: 20,
    fontWeight: '800',
  },
  limitTitleRow: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 12,
    minWidth: 0,
  },
  limitTrack: {
    backgroundColor: '#EDF2F7',
    borderRadius: 8,
    height: 14,
    overflow: 'hidden',
    width: '100%',
  },
  name: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 18,
    fontWeight: '800',
  },
  pageContent: {
    paddingBottom: 32,
  },
  primaryWalletAmount: {
    color: colors.primary,
  },
  primaryWalletIcon: {
    backgroundColor: colors.primary,
  },
  primaryWalletOption: {
    backgroundColor: 'rgba(255, 204, 213, 0.36)',
    borderColor: 'rgba(238, 43, 108, 0.16)',
  },
  purpleWalletAmount: {
    color: '#9333EA',
  },
  purpleWalletIcon: {
    backgroundColor: '#A855F7',
  },
  purpleWalletOption: {
    backgroundColor: 'rgba(168, 85, 247, 0.13)',
    borderColor: 'rgba(168, 85, 247, 0.16)',
  },
  ringBlue: {
    backgroundColor: colors.secondary,
    height: 86,
    left: 0,
    top: 86,
    width: 86,
  },
  ringPrimary: {
    backgroundColor: colors.primary,
    height: 172,
    right: 0,
    top: 0,
    width: 86,
  },
  ringPurple: {
    backgroundColor: colors.accentPurple,
    height: 86,
    right: 0,
    top: 0,
    width: 86,
  },
  ringSegment: {
    position: 'absolute',
  },
  ringYellow: {
    backgroundColor: colors.tertiary,
    height: 86,
    left: 0,
    top: 0,
    width: 86,
  },
  section: {
    marginTop: 28,
    paddingHorizontal: 24,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  sectionLink: {
    color: colors.primary,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  sectionTitle: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 20,
    fontWeight: '800',
  },
  sheetCloseButton: {
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  sheetCloseText: {
    color: colors.slate400,
    fontSize: 26,
    lineHeight: 28,
  },
  sheetContainer: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingBottom: 32,
    paddingHorizontal: 24,
    paddingTop: 12,
    width: '100%',
  },
  sheetHandle: {
    alignSelf: 'center',
    backgroundColor: colors.accentPink,
    borderRadius: 4,
    height: 8,
    marginBottom: 24,
    width: 72,
  },
  sheetHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  sheetIconText: {
    color: colors.white,
    fontSize: 22,
    fontWeight: '800',
  },
  sheetTitle: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 22,
    fontWeight: '800',
  },
  sheetTitleArea: {
    flex: 1,
  },
  summaryGrid: {
    flexDirection: 'row',
    gap: 18,
    marginTop: 28,
    paddingHorizontal: 24,
  },
  summaryCard: {
    alignItems: 'flex-start',
    flex: 1,
    gap: 12,
  },
  summaryIcon: {
    color: colors.white,
    fontSize: 22,
    fontWeight: '800',
  },
  summaryIconBox: {
    alignItems: 'center',
    borderRadius: 18,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  summaryLabel: {
    color: colors.slate600,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 16,
  },
  summaryValue: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 16,
    fontWeight: '800',
  },
  transactionAmount: {
    fontFamily: typography.fontFamily,
    fontSize: 14,
    fontWeight: '800',
  },
  totalWalletAmount: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 16,
    fontWeight: '800',
  },
  totalWalletCopy: {
    flex: 1,
  },
  totalWalletIcon: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 24,
    height: 56,
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.24,
    shadowRadius: 12,
    width: 56,
  },
  totalWalletOption: {
    alignItems: 'center',
    backgroundColor: 'rgba(238, 43, 108, 0.05)',
    borderColor: 'rgba(238, 43, 108, 0.22)',
    borderRadius: 22,
    borderWidth: 2,
    flexDirection: 'row',
    gap: 14,
    marginBottom: 24,
    padding: 18,
  },
  totalWalletSubtitle: {
    color: colors.slate600,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
  },
  totalWalletTitle: {
    color: colors.primary,
    fontFamily: typography.fontFamily,
    fontSize: 16,
    fontWeight: '800',
  },
  walletGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  walletOption: {
    borderRadius: 22,
    borderWidth: 1,
    flexBasis: '47%',
    gap: 8,
    minHeight: 142,
    padding: 18,
  },
  walletOptionAmount: {
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  walletOptionIcon: {
    alignItems: 'center',
    borderRadius: 18,
    height: 44,
    justifyContent: 'center',
    marginBottom: 12,
    shadowColor: colors.slate900,
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    width: 44,
  },
  walletOptionName: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 14,
    fontWeight: '800',
  },
  yellowWalletAmount: {
    color: '#CA8A04',
  },
  yellowWalletIcon: {
    backgroundColor: '#EAB308',
  },
  yellowWalletOption: {
    backgroundColor: 'rgba(251, 207, 51, 0.25)',
    borderColor: 'rgba(234, 179, 8, 0.22)',
  },
});

export default styles;
