import { StyleSheet } from 'react-native';

import { colors, typography } from '../../Theme';

const styles = StyleSheet.create({
  card: {
    backgroundColor: 'rgba(255, 255, 255, 0.88)',
    borderColor: 'rgba(255, 204, 213, 0.32)',
    borderRadius: 32,
    borderWidth: 1,
    padding: 28,
    shadowColor: colors.slate900,
    shadowOffset: { height: 18, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    width: '100%',
  },
  container: {
    backgroundColor: colors.white,
    flex: 1,
  },
  emailIcon: {
    borderColor: colors.accentPink,
    borderRadius: 3,
    borderWidth: 2,
    height: 18,
    overflow: 'hidden',
    width: 24,
  },
  emailIconFlapLeft: {
    backgroundColor: colors.accentPink,
    height: 2,
    left: 1,
    position: 'absolute',
    top: 5,
    transform: [{ rotate: '32deg' }],
    width: 13,
  },
  emailIconFlapRight: {
    backgroundColor: colors.accentPink,
    height: 2,
    position: 'absolute',
    right: 1,
    top: 5,
    transform: [{ rotate: '-32deg' }],
    width: 13,
  },
  eyeButton: {
    padding: 14,
    position: 'absolute',
    right: 0,
  },
  eyeArcBottom: {
    borderBottomWidth: 2,
    borderColor: colors.slate400,
    borderLeftWidth: 2,
    borderRadius: 18,
    borderRightWidth: 2,
    bottom: 4,
    height: 16,
    position: 'absolute',
    transform: [{ scaleY: 0.58 }],
    width: 26,
  },
  eyeArcTop: {
    borderColor: colors.slate400,
    borderLeftWidth: 2,
    borderRadius: 18,
    borderRightWidth: 2,
    borderTopWidth: 2,
    height: 16,
    position: 'absolute',
    top: 4,
    transform: [{ scaleY: 0.58 }],
    width: 26,
  },
  eyeIconContainer: {
    alignItems: 'center',
    height: 24,
    justifyContent: 'center',
    width: 30,
  },
  eyePupil: {
    backgroundColor: colors.slate400,
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  errorText: {
    color: colors.primary,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 14,
    marginTop: -6,
    textAlign: 'center',
  },
  fieldGroup: {
    gap: 8,
    marginBottom: 18,
  },
  forgotButton: {
    alignItems: 'flex-end',
    marginBottom: 28,
  },
  forgotText: {
    color: colors.accentPurple,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '700',
  },
  header: {
    alignItems: 'center',
    marginBottom: 30,
  },
  input: {
    color: colors.slate900,
    flex: 1,
    fontFamily: typography.fontFamily,
    fontSize: 16,
    fontWeight: '500',
    paddingRight: 42,
  },
  inputIcon: {
    alignItems: 'center',
    height: 26,
    justifyContent: 'center',
    marginRight: 16,
    width: 26,
  },
  inputWrapper: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 204, 213, 0.18)',
    borderRadius: 18,
    flexDirection: 'row',
    minHeight: 64,
    paddingHorizontal: 18,
  },
  label: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    marginLeft: 12,
  },
  loginButton: {
    alignItems: 'center',
    backgroundColor: colors.accentPink,
    borderRadius: 18,
    justifyContent: 'center',
    minHeight: 64,
    shadowColor: colors.accentPink,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.42,
    shadowRadius: 18,
  },
  loginButtonDisabled: {
    opacity: 0.52,
  },
  loginButtonText: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 16,
    fontWeight: '800',
  },
  lockBody: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 204, 213, 0.14)',
    borderColor: colors.accentPink,
    borderRadius: 4,
    borderWidth: 2,
    height: 17,
    justifyContent: 'center',
    marginTop: 8,
    width: 22,
  },
  lockIcon: {
    alignItems: 'center',
    height: 26,
    justifyContent: 'flex-end',
    width: 26,
  },
  lockKeyhole: {
    backgroundColor: colors.accentPink,
    borderRadius: 2,
    height: 5,
    width: 4,
  },
  lockShackle: {
    borderColor: colors.accentPink,
    borderRadius: 8,
    borderWidth: 2,
    height: 16,
    position: 'absolute',
    top: 0,
    width: 15,
  },
  logo: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 204, 213, 0.22)',
    borderColor: colors.white,
    borderRadius: 48,
    borderWidth: 4,
    height: 96,
    justifyContent: 'center',
    marginBottom: 28,
    shadowColor: colors.slate900,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    width: 96,
  },
  logoBadge: {
    alignItems: 'center',
    backgroundColor: colors.accentPurple,
    borderRadius: 14,
    bottom: 14,
    height: 28,
    justifyContent: 'center',
    position: 'absolute',
    right: 10,
    width: 28,
  },
  logoBadgeIcon: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '800',
  },
  logoIcon: {
    color: colors.accentPink,
    fontSize: 48,
    fontWeight: '800',
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 24,
  },
  subtitle: {
    color: colors.slate600,
    fontFamily: typography.fontFamily,
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 21,
    maxWidth: 280,
    textAlign: 'center',
  },
  successText: {
    color: colors.secondary,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 14,
    marginTop: -6,
    textAlign: 'center',
  },
  title: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 36,
    fontWeight: '800',
    lineHeight: 43,
    marginBottom: 12,
    textAlign: 'center',
  },
  switchModeAction: {
    color: colors.primary,
    fontWeight: '800',
  },
  switchModeButton: {
    alignItems: 'center',
    marginTop: 20,
  },
  switchModeText: {
    color: colors.slate600,
    fontFamily: typography.fontFamily,
    fontSize: 13,
    fontWeight: '600',
  },
  userBody: {
    borderColor: colors.accentPink,
    borderRadius: 9,
    borderWidth: 2,
    height: 11,
    width: 22,
  },
  userHead: {
    borderColor: colors.accentPink,
    borderRadius: 6,
    borderWidth: 2,
    height: 12,
    marginBottom: 2,
    width: 12,
  },
  userIcon: {
    alignItems: 'center',
    height: 26,
    justifyContent: 'center',
    width: 26,
  },
});

export default styles;
