import { StyleSheet } from 'react-native';

import { colors, typography } from '../../../../Theme';

const styles = StyleSheet.create({
  confirmButton: {
    alignItems: 'center',
    backgroundColor: colors.slate900,
    borderRadius: 18,
    marginTop: 28,
    paddingVertical: 18,
    shadowColor: colors.slate900,
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
  },
  confirmButtonText: {
    color: colors.white,
    fontFamily: typography.fontFamily,
    fontSize: 15,
    fontWeight: '800',
  },
  fullHistoryAmount: {
    flexShrink: 0,
    fontFamily: typography.fontFamily,
    fontSize: 18,
    fontWeight: '800',
    maxWidth: 148,
    textAlign: 'right',
  },
  fullHistoryAmountExpense: {
    color: colors.slate900,
  },
  fullHistoryAmountIncome: {
    color: colors.accentPurple,
  },
  fullHistoryAmountTransfer: {
    color: colors.slate600,
  },
  fullHistoryChip: {
    backgroundColor: colors.white,
    borderColor: 'rgba(255, 204, 213, 0.24)',
    borderRadius: 22,
    borderWidth: 1,
    paddingHorizontal: 22,
    paddingVertical: 12,
    shadowColor: colors.slate900,
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 5,
  },
  fullHistoryChipActive: {
    backgroundColor: colors.slate900,
    borderColor: colors.slate900,
  },
  fullHistoryChipRow: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 24,
  },
  fullHistoryChipText: {
    color: colors.slate600,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  fullHistoryChipTextActive: {
    color: colors.white,
  },
  fullHistoryContainer: {
    backgroundColor: colors.backgroundLight,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    maxHeight: '88%',
    overflow: 'hidden',
    width: '100%',
  },
  fullHistoryContent: {
    gap: 28,
    paddingBottom: 36,
    paddingHorizontal: 0,
    paddingTop: 22,
  },
  fullHistoryEmptyState: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderColor: 'rgba(238, 43, 108, 0.05)',
    borderRadius: 22,
    borderWidth: 1,
    marginHorizontal: 24,
    padding: 24,
  },
  fullHistoryEmptyText: {
    color: colors.slate400,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 6,
    textAlign: 'center',
  },
  fullHistoryEmptyTitle: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 16,
    fontWeight: '800',
  },
  fullHistoryGroup: {
    gap: 12,
  },
  fullHistoryGroupTitle: {
    color: colors.slate400,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.2,
    paddingHorizontal: 24,
    textTransform: 'uppercase',
  },
  fullHistoryHandle: {
    alignSelf: 'center',
    backgroundColor: '#DDE3EC',
    borderRadius: 4,
    height: 8,
    marginBottom: 22,
    width: 56,
  },
  fullHistoryHeader: {
    backgroundColor: 'rgba(255, 255, 255, 0.66)',
    borderBottomColor: 'rgba(255, 204, 213, 0.18)',
    borderBottomWidth: 1,
    paddingBottom: 16,
    paddingTop: 14,
  },
  fullHistoryLoadingState: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderColor: 'rgba(238, 43, 108, 0.05)',
    borderRadius: 22,
    borderWidth: 1,
    justifyContent: 'center',
    marginHorizontal: 24,
    minHeight: 220,
    padding: 24,
  },
  fullHistoryIcon: {
    color: colors.primary,
    fontSize: 22,
    fontWeight: '800',
  },
  fullHistoryIconBox: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 204, 213, 0.28)',
    borderRadius: 20,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  fullHistoryItem: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderColor: 'rgba(238, 43, 108, 0.05)',
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 24,
    minHeight: 90,
    padding: 16,
    shadowColor: colors.slate900,
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
  },
  fullHistoryItemCopy: {
    flex: 1,
    minWidth: 0,
  },
  fullHistoryItemIcon: {
    color: colors.primary,
    fontSize: 24,
    fontWeight: '800',
  },
  fullHistoryItemIconBox: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 204, 213, 0.32)',
    borderRadius: 28,
    height: 56,
    justifyContent: 'center',
    width: 56,
  },
  fullHistoryItemLeft: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 14,
    minWidth: 0,
  },
  fullHistoryItemMeta: {
    color: colors.slate400,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 4,
  },
  fullHistoryItemTitle: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 16,
    fontWeight: '800',
  },
  fullHistoryList: {
    gap: 12,
  },
  fullHistoryMonth: {
    backgroundColor: colors.white,
    borderColor: 'rgba(255, 204, 213, 0.22)',
    borderRadius: 18,
    borderWidth: 1,
    color: colors.slate600,
    fontFamily: typography.fontFamily,
    fontSize: 13,
    fontWeight: '800',
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  fullHistoryPeriodContent: {
    gap: 16,
    paddingBottom: 32,
    paddingHorizontal: 24,
  },
  fullHistoryTitle: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 24,
    fontWeight: '800',
  },
  fullHistoryTitleLeft: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 14,
  },
  fullHistoryTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    marginBottom: 22,
    paddingHorizontal: 24,
  },
  fullHistoryWalletDropdownArea: {
    paddingHorizontal: 24,
    position: 'relative',
    zIndex: 20,
  },
  fullHistoryWalletDropdownButton: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderColor: 'rgba(255, 204, 213, 0.24)',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    shadowColor: colors.slate900,
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.04,
    shadowRadius: 5,
  },
  fullHistoryWalletDropdownIcon: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '800',
  },
  fullHistoryWalletDropdownOption: {
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  fullHistoryWalletDropdownOptionActive: {
    backgroundColor: 'rgba(238, 43, 108, 0.1)',
  },
  fullHistoryWalletDropdownOptions: {
    backgroundColor: colors.white,
    borderColor: 'rgba(255, 204, 213, 0.24)',
    borderRadius: 18,
    borderWidth: 1,
    gap: 3,
    left: 24,
    padding: 6,
    position: 'absolute',
    right: 24,
    top: 52,
    zIndex: 40,
  },
  fullHistoryWalletDropdownOptionText: {
    color: colors.slate600,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  fullHistoryWalletDropdownOptionTextActive: {
    color: colors.primary,
  },
  fullHistoryWalletDropdownText: {
    color: colors.slate600,
    flex: 1,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  historyAmountExpense: {
    color: colors.primary,
  },
  historyAmountIncome: {
    color: colors.secondary,
  },
  historyAmountText: {
    flexShrink: 0,
    fontFamily: typography.fontFamily,
    fontSize: 13,
    fontWeight: '800',
    maxWidth: 118,
    textAlign: 'right',
  },
  historyAmountTransfer: {
    color: colors.slate600,
  },
  historyCopy: {
    flex: 1,
    minWidth: 0,
  },
  historyEmptyState: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderColor: 'rgba(238, 43, 108, 0.05)',
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: 20,
    paddingVertical: 28,
  },
  historyEmptyText: {
    color: colors.slate400,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 6,
    textAlign: 'center',
  },
  historyEmptyTitle: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 16,
    fontWeight: '800',
  },
  historyGroup: {
    gap: 10,
  },
  historyGroupTitle: {
    color: colors.slate400,
    fontFamily: typography.fontFamily,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
    marginLeft: 4,
    textTransform: 'uppercase',
  },
  historyIcon: {
    fontSize: 22,
  },
  historyIconBox: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 204, 213, 0.45)',
    borderRadius: 16,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  historyLoadingSpinner: {
    color: colors.primary,
  },
  historyLoadingState: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderColor: 'rgba(238, 43, 108, 0.05)',
    borderRadius: 24,
    borderWidth: 1,
    gap: 10,
    justifyContent: 'center',
    minHeight: 116,
    paddingHorizontal: 20,
    paddingVertical: 28,
  },
  historyLoadingText: {
    color: colors.slate400,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },
  historyItem: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 24,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    minHeight: 74,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  historyLeft: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 12,
    minWidth: 0,
  },
  historyList: {
    gap: 12,
  },
  historyMeta: {
    color: colors.slate400,
    fontFamily: typography.fontFamily,
    fontSize: 10,
    fontWeight: '500',
  },
  historyTitle: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 14,
    fontWeight: '800',
  },
  periodGroupTitle: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 13,
    fontWeight: '800',
    marginLeft: 4,
  },
  periodOption: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 204, 213, 0.14)',
    borderColor: 'rgba(255, 204, 213, 0.32)',
    borderRadius: 16,
    borderWidth: 1,
    flexBasis: '22%',
    paddingVertical: 12,
  },
  periodOptionActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  periodOptionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 8,
  },
  periodOptionText: {
    color: colors.slate600,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  periodOptionTextActive: {
    color: colors.white,
  },
  section: {
    marginTop: 28,
    paddingHorizontal: 24,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  sectionLink: {
    color: colors.primary,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  sectionTitle: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 20,
    fontWeight: '800',
  },
  sheetBackButton: {
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    marginRight: 12,
    width: 36,
  },
  sheetBackText: {
    color: colors.slate600,
    fontSize: 30,
    fontWeight: '800',
    lineHeight: 32,
  },
  sheetCloseButton: {
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  sheetCloseText: {
    color: colors.slate400,
    fontSize: 26,
    lineHeight: 28,
  },
  sheetHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
    paddingHorizontal: 24,
  },
  sheetTitle: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 22,
    fontWeight: '800',
  },
  sheetTitleArea: {
    flex: 1,
  },
});

export default styles;
