type CategoryIconPreset = {
  icon: string;
  label: string;
};

const categoryIconPresets: CategoryIconPreset[] = [
  { icon: 'lunch_dining', label: 'Makan' },
  { icon: 'two_wheeler', label: 'Transport' },
  { icon: 'shopping_bag', label: 'Belanja' },
  { icon: 'wifi', label: 'Internet' },
  { icon: 'home', label: 'Rumah' },
  { icon: 'favorite', label: 'Hobi' },
  { icon: 'local_cafe', label: 'Kopi' },
  { icon: 'restaurant', label: 'Restoran' },
  { icon: 'directions_car', label: 'Mobil' },
  { icon: 'local_gas_station', label: 'Bensin' },
  { icon: 'local_parking', label: 'Parkir' },
  { icon: 'train', label: 'Kereta' },
  { icon: 'flight', label: 'Travel' },
  { icon: 'hotel', label: 'Hotel' },
  { icon: 'bolt', label: 'Listrik' },
  { icon: 'water_drop', label: 'Air' },
  { icon: 'phone_iphone', label: 'Pulsa' },
  { icon: 'subscriptions', label: 'Langganan' },
  { icon: 'movie', label: 'Nonton' },
  { icon: 'sports_esports', label: 'Game' },
  { icon: 'sports_soccer', label: 'Olahraga' },
  { icon: 'celebration', label: 'Hadiah' },
  { icon: 'family_restroom', label: 'Keluarga' },
  { icon: 'child_care', label: 'Anak' },
  { icon: 'school', label: 'Sekolah' },
  { icon: 'work', label: 'Kerja' },
  { icon: 'face_6', label: 'Skincare' },
  { icon: 'spa', label: 'Salon' },
  { icon: 'medical_services', label: 'Obat' },
  { icon: 'diversity_3', label: 'Arisan' },
  { icon: 'request_quote', label: 'Pinjaman' },
  { icon: 'credit_card', label: 'Cicilan' },
  { icon: 'account_balance', label: 'Bank' },
  { icon: 'savings', label: 'Tabungan' },
  { icon: 'trending_up', label: 'Investasi' },
  { icon: 'icecream', label: 'Jajanan' },
  { icon: 'emergency_home', label: 'Darurat' },
  { icon: 'local_hospital', label: 'Rumah Sakit' },
  { icon: 'pets', label: 'Peliharaan' },
  { icon: 'volunteer_activism', label: 'Donasi' },
  { icon: 'cleaning_services', label: 'Laundry' },
  { icon: 'build', label: 'Service' },
  { icon: 'receipt_long', label: 'Pajak' },
];

const categoryIconMap: Record<string, string> = {
  account_balance: '🏦',
  bolt: '⚡',
  build: '🛠️',
  celebration: '🎁',
  child_care: '🧸',
  cleaning_services: '🧺',
  credit_card: '💳',
  directions_car: '🚗',
  diversity_3: '🤝',
  emergency_home: '🧯',
  face_6: '🧴',
  family_restroom: '👨‍👩‍👧',
  favorite: '💖',
  flight: '✈️',
  home: '🏠',
  home_pin: '🏠',
  hotel: '🏨',
  icecream: '🍦',
  local_cafe: '☕',
  local_gas_station: '⛽',
  local_hospital: '🏥',
  local_parking: '🅿️',
  lunch_dining: '🍜',
  medical_services: '💊',
  movie: '🎬',
  payments: '💸',
  pets: '🐾',
  phone_iphone: '📱',
  receipt_long: '🧾',
  restaurant: '🍱',
  request_quote: '🧾',
  savings: '🐷',
  school: '📚',
  shopping_bag: '🛍️',
  spa: '🌸',
  sports_esports: '🎮',
  sports_soccer: '⚽',
  subscriptions: '📺',
  train: '🚆',
  trending_up: '📈',
  two_wheeler: '🚗',
  volunteer_activism: '💝',
  water_drop: '💧',
  wifi: '📶',
  work: '💼',
};

function getCategoryIconValue(icon: string) {
  return categoryIconMap[icon] ?? '✨';
}

export {
  categoryIconPresets,
  getCategoryIconValue,
};
