import { StyleSheet } from 'react-native';

import { colors, typography } from '../../Theme';

const styles = StyleSheet.create({
  amountBox: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 245, 247, 0.66)',
    borderColor: 'rgba(255, 204, 213, 0.42)',
    borderRadius: 24,
    borderWidth: 1,
    marginBottom: 24,
    padding: 22,
  },
  amountInput: {
    color: colors.slate900,
    flex: 1,
    fontFamily: typography.fontFamily,
    fontSize: 36,
    fontWeight: '800',
    padding: 0,
    textAlign: 'center',
  },
  amountLabel: {
    color: colors.slate400,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 12,
  },
  amountRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  backButton: {
    alignItems: 'center',
    backgroundColor: colors.backgroundLight,
    borderRadius: 24,
    height: 48,
    justifyContent: 'center',
    marginRight: 12,
    width: 48,
  },
  backText: {
    color: colors.slate600,
    fontSize: 34,
    lineHeight: 34,
  },
  categoryCircle: {
    alignItems: 'center',
    backgroundColor: colors.backgroundLight,
    borderColor: 'rgba(255, 204, 213, 0.46)',
    borderRadius: 29,
    borderWidth: 1,
    height: 58,
    justifyContent: 'center',
    width: 58,
  },
  categoryCircleActive: {
    backgroundColor: colors.accentPink,
    borderColor: colors.white,
    borderWidth: 2,
    shadowColor: colors.primary,
    shadowOffset: { height: 5, width: 0 },
    shadowOpacity: 0.16,
    shadowRadius: 8,
  },
  categoryIcon: {
    color: colors.slate600,
    fontSize: 28,
    fontWeight: '800',
  },
  categoryIconActive: {
    color: colors.slate900,
  },
  categoryItem: {
    alignItems: 'center',
    flexDirection: 'column',
    gap: 8,
    minWidth: 72,
  },
  categoryLabel: {
    color: colors.slate600,
    fontFamily: typography.fontFamily,
    fontSize: 10,
    fontWeight: '800',
  },
  categoryLabelActive: {
    color: colors.slate900,
  },
  categoryRow: {
    flexDirection: 'row',
    gap: 16,
    paddingHorizontal: 2,
    paddingVertical: 4,
  },
  choiceChip: {
    backgroundColor: 'rgba(255, 204, 213, 0.14)',
    borderColor: 'rgba(255, 204, 213, 0.32)',
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  choiceChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  choiceRow: {
    flexDirection: 'row',
    gap: 10,
    paddingVertical: 4,
  },
  choiceText: {
    color: colors.slate600,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  choiceTextActive: {
    color: colors.white,
  },
  closeButton: {
    alignItems: 'center',
    backgroundColor: colors.backgroundLight,
    borderRadius: 24,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  closeText: {
    color: colors.slate600,
    fontSize: 34,
    lineHeight: 36,
  },
  container: {
    backgroundColor: colors.white,
    borderColor: 'rgba(255, 204, 213, 0.28)',
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    borderTopWidth: 1,
    maxHeight: '90%',
    paddingTop: 14,
  },
  deleteButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(238, 43, 108, 0.08)',
    borderColor: 'rgba(238, 43, 108, 0.24)',
    borderRadius: 20,
    borderWidth: 1,
    marginBottom: 12,
    paddingVertical: 14,
  },
  deleteButtonText: {
    color: colors.primary,
    fontFamily: typography.fontFamily,
    fontSize: 14,
    fontWeight: '800',
  },
  content: {
    paddingBottom: 176,
    paddingHorizontal: 24,
  },
  confirmationCard: {
    backgroundColor: 'rgba(255, 245, 247, 0.52)',
    borderColor: 'rgba(255, 204, 213, 0.34)',
    borderRadius: 24,
    borderWidth: 1,
    gap: 18,
    padding: 22,
  },
  confirmationEyebrow: {
    color: colors.primary,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  confirmationTitle: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 8,
  },
  field: {
    flex: 1,
    gap: 8,
  },
  dragHandleArea: {
    paddingTop: 0,
  },
  footer: {
    backgroundColor: 'rgba(255, 255, 255, 0.94)',
    borderColor: 'rgba(255, 204, 213, 0.2)',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderTopWidth: 1,
    bottom: 0,
    left: 0,
    padding: 24,
    position: 'absolute',
    right: 0,
  },
  handle: {
    alignSelf: 'center',
    backgroundColor: '#DDE3EC',
    borderRadius: 4,
    height: 8,
    marginBottom: 28,
    width: 56,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 26,
    paddingHorizontal: 24,
  },
  headerTitleArea: {
    flex: 1,
  },
  inputPrefix: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 18,
    fontWeight: '800',
  },
  noteInput: {
    borderColor: 'rgba(255, 204, 213, 0.34)',
    borderRadius: 16,
    borderWidth: 1,
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 15,
    fontWeight: '500',
    minHeight: 86,
    paddingHorizontal: 16,
    paddingVertical: 14,
    textAlignVertical: 'top',
  },
  titleInput: {
    borderColor: 'rgba(255, 204, 213, 0.34)',
    borderRadius: 16,
    borderWidth: 1,
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 15,
    fontWeight: '600',
    minHeight: 56,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  notesSection: {
    marginTop: 24,
  },
  errorText: {
    color: colors.primary,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 10,
    textAlign: 'center',
  },
  pickerSection: {
    gap: 12,
    marginBottom: 22,
  },
  saveButton: {
    alignItems: 'center',
    backgroundColor: colors.slate900,
    borderRadius: 24,
    paddingVertical: 18,
    shadowColor: colors.slate900,
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
  },
  saveText: {
    color: colors.white,
    fontFamily: typography.fontFamily,
    fontSize: 16,
    fontWeight: '800',
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: colors.backgroundLight,
    borderColor: 'rgba(255, 204, 213, 0.28)',
    borderRadius: 20,
    borderWidth: 1,
    marginBottom: 12,
    paddingVertical: 14,
  },
  secondaryButtonText: {
    color: colors.slate600,
    fontFamily: typography.fontFamily,
    fontSize: 14,
    fontWeight: '800',
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  sectionLink: {
    color: colors.accentPurple,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  sectionTitle: {
    color: colors.slate600,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  segment: {
    backgroundColor: colors.backgroundLight,
    borderColor: 'rgba(255, 204, 213, 0.18)',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    marginBottom: 24,
    padding: 4,
  },
  segmentButton: {
    alignItems: 'center',
    borderRadius: 12,
    flex: 1,
    paddingVertical: 12,
  },
  segmentButtonActive: {
    backgroundColor: colors.white,
    shadowColor: colors.slate900,
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
  },
  segmentText: {
    color: colors.slate600,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  segmentTextActive: {
    color: colors.slate900,
  },
  summaryLabel: {
    color: colors.slate400,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  summaryRow: {
    borderBottomColor: 'rgba(255, 204, 213, 0.22)',
    borderBottomWidth: 1,
    gap: 8,
    paddingBottom: 14,
  },
  summaryValue: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 16,
    fontWeight: '800',
  },
  title: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 26,
    fontWeight: '800',
  },
});

export default styles;
