import { StyleSheet } from 'react-native';

import { colors, typography } from '../../../../Theme';

const styles = StyleSheet.create({
  addWalletButton: {
    alignItems: 'center',
    backgroundColor: colors.white,
    borderColor: 'rgba(238, 43, 108, 0.3)',
    borderRadius: 22,
    borderStyle: 'dashed',
    borderWidth: 2,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    marginTop: 26,
    paddingVertical: 19,
  },
  addWalletIcon: {
    color: colors.primary,
    fontSize: 24,
    fontWeight: '800',
    lineHeight: 26,
  },
  addWalletText: {
    color: colors.primary,
    fontFamily: typography.fontFamily,
    fontSize: 15,
    fontWeight: '800',
  },
  balanceBadge: {
    backgroundColor: 'rgba(255, 255, 255, 0.24)',
    borderColor: 'rgba(255, 255, 255, 0.22)',
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  balanceBadgeText: {
    color: colors.white,
    fontFamily: typography.fontFamily,
    fontSize: 10,
    fontWeight: '800',
  },
  balanceCard: {
    backgroundColor: colors.primary,
    borderRadius: 22,
    marginHorizontal: 24,
    marginTop: 22,
    overflow: 'hidden',
    padding: 22,
    shadowColor: colors.primary,
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.24,
    shadowRadius: 18,
  },
  balanceHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  balanceLabel: {
    color: colors.white,
    fontFamily: typography.fontFamily,
    fontSize: 14,
    fontWeight: '800',
    opacity: 0.94,
  },
  balanceNote: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    borderRadius: 18,
    color: colors.white,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 14,
    paddingHorizontal: 16,
    paddingVertical: 7,
  },
  balancePattern: {
    bottom: -20,
    color: colors.white,
    fontSize: 180,
    opacity: 0.06,
    position: 'absolute',
    right: -18,
  },
  balanceValue: {
    color: colors.white,
    fontFamily: typography.fontFamily,
    fontSize: 34,
    fontWeight: '800',
  },
  blueWalletAmount: {
    color: colors.secondary,
  },
  blueWalletIcon: {
    backgroundColor: colors.secondary,
  },
  blueWalletOption: {
    backgroundColor: 'rgba(202, 240, 248, 0.55)',
    borderColor: 'rgba(78, 168, 222, 0.16)',
  },
  primaryWalletAmount: {
    color: colors.primary,
  },
  primaryWalletIcon: {
    backgroundColor: colors.primary,
  },
  primaryWalletOption: {
    backgroundColor: 'rgba(255, 204, 213, 0.36)',
    borderColor: 'rgba(238, 43, 108, 0.16)',
  },
  purpleWalletAmount: {
    color: '#9333EA',
  },
  purpleWalletIcon: {
    backgroundColor: '#A855F7',
  },
  purpleWalletOption: {
    backgroundColor: 'rgba(168, 85, 247, 0.13)',
    borderColor: 'rgba(168, 85, 247, 0.16)',
  },
  saveWalletButton: {
    alignItems: 'center',
    backgroundColor: colors.slate900,
    borderRadius: 18,
    marginTop: 10,
    paddingVertical: 18,
    shadowColor: colors.slate900,
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
  },
  saveWalletButtonText: {
    color: colors.white,
    fontFamily: typography.fontFamily,
    fontSize: 15,
    fontWeight: '800',
  },
  sheetBackButton: {
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    marginRight: 12,
    width: 36,
  },
  sheetBackText: {
    color: colors.slate600,
    fontSize: 30,
    fontWeight: '800',
    lineHeight: 32,
  },
  sheetCloseButton: {
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  sheetCloseText: {
    color: colors.slate400,
    fontSize: 26,
    lineHeight: 28,
  },
  sheetContainer: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingBottom: 32,
    paddingHorizontal: 24,
    paddingTop: 12,
    width: '100%',
  },
  sheetHandle: {
    alignSelf: 'center',
    backgroundColor: colors.accentPink,
    borderRadius: 4,
    height: 8,
    marginBottom: 24,
    width: 72,
  },
  sheetHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  sheetIconText: {
    color: colors.white,
    fontSize: 22,
    fontWeight: '800',
  },
  sheetTitle: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 22,
    fontWeight: '800',
  },
  sheetTitleArea: {
    flex: 1,
  },
  totalWalletAmount: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 16,
    fontWeight: '800',
  },
  totalWalletCopy: {
    flex: 1,
  },
  totalWalletIcon: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 24,
    height: 56,
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.24,
    shadowRadius: 12,
    width: 56,
  },
  totalWalletOption: {
    alignItems: 'center',
    backgroundColor: 'rgba(238, 43, 108, 0.05)',
    borderColor: 'rgba(238, 43, 108, 0.22)',
    borderRadius: 22,
    borderWidth: 2,
    flexDirection: 'row',
    gap: 14,
    marginBottom: 24,
    padding: 18,
  },
  totalWalletSubtitle: {
    color: colors.slate600,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
  },
  totalWalletTitle: {
    color: colors.primary,
    fontFamily: typography.fontFamily,
    fontSize: 16,
    fontWeight: '800',
  },
  walletDeleteButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderColor: colors.white,
    borderRadius: 14,
    borderWidth: 2,
    height: 28,
    justifyContent: 'center',
    position: 'absolute',
    right: 10,
    top: 10,
    width: 28,
    zIndex: 2,
  },
  walletDeleteText: {
    color: colors.white,
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 22,
  },
  walletEditButton: {
    alignItems: 'center',
    backgroundColor: colors.secondary,
    borderColor: colors.white,
    borderRadius: 14,
    borderWidth: 2,
    height: 28,
    justifyContent: 'center',
    position: 'absolute',
    right: 10,
    top: 10,
    width: 28,
    zIndex: 2,
  },
  walletEditText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 16,
  },
  walletEmptyState: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 204, 213, 0.1)',
    borderColor: 'rgba(238, 43, 108, 0.16)',
    borderRadius: 22,
    borderWidth: 1,
    paddingHorizontal: 18,
    paddingVertical: 28,
  },
  walletEmptyText: {
    color: colors.slate400,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
    maxWidth: 220,
    textAlign: 'center',
  },
  walletEmptyTitle: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 4,
  },
  walletForm: {
    gap: 18,
  },
  walletFormError: {
    color: colors.primary,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    marginTop: -6,
    textAlign: 'center',
  },
  walletFormField: {
    gap: 8,
  },
  walletFormInput: {
    backgroundColor: 'rgba(255, 204, 213, 0.16)',
    borderColor: 'rgba(255, 204, 213, 0.34)',
    borderRadius: 18,
    borderWidth: 1,
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 15,
    fontWeight: '700',
    minHeight: 60,
    paddingHorizontal: 18,
  },
  walletFormLabel: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
    marginLeft: 8,
  },
  walletGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  walletHeaderActions: {
    flexDirection: 'row',
  },
  walletOption: {
    borderRadius: 22,
    borderWidth: 1,
    flexBasis: '47%',
    gap: 8,
    minHeight: 142,
    padding: 18,
  },
  walletOptionAmount: {
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  walletOptionIcon: {
    alignItems: 'center',
    borderRadius: 18,
    height: 44,
    justifyContent: 'center',
    marginBottom: 12,
    shadowColor: colors.slate900,
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    width: 44,
  },
  walletOptionName: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 14,
    fontWeight: '800',
  },
  walletTrashButton: {
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    marginRight: 10,
    width: 36,
  },
  walletTrashButtonActive: {
    backgroundColor: 'rgba(238, 43, 108, 0.14)',
  },
  walletTrashButtonDisabled: {
    opacity: 0.38,
  },
  walletTrashText: {
    fontSize: 18,
    lineHeight: 21,
  },
  walletTypeChip: {
    backgroundColor: 'rgba(255, 204, 213, 0.14)',
    borderColor: 'rgba(255, 204, 213, 0.32)',
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  walletTypeChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  walletTypeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  walletTypeText: {
    color: colors.slate600,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
  },
  walletTypeTextActive: {
    color: colors.white,
  },
  yellowWalletAmount: {
    color: '#CA8A04',
  },
  yellowWalletIcon: {
    backgroundColor: '#EAB308',
  },
  yellowWalletOption: {
    backgroundColor: 'rgba(251, 207, 51, 0.25)',
    borderColor: 'rgba(234, 179, 8, 0.22)',
  },
});

export default styles;
