import { StyleSheet } from 'react-native';

import { colors, typography } from '../../../../Theme';

const styles = StyleSheet.create({
  actionGroup: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  avatar: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 204, 213, 0.78)',
    borderColor: 'rgba(238, 43, 108, 0.24)',
    borderRadius: 30,
    borderWidth: 3,
    height: 60,
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 14,
    width: 60,
  },
  avatarText: {
    color: colors.primary,
    fontFamily: typography.fontFamily,
    fontSize: 24,
    fontWeight: '800',
  },
  cancelButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 204, 213, 0.18)',
    borderRadius: 18,
    flex: 1,
    paddingVertical: 17,
  },
  cancelButtonText: {
    color: colors.primary,
    fontFamily: typography.fontFamily,
    fontSize: 14,
    fontWeight: '800',
  },
  editButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(238, 43, 108, 0.1)',
    borderColor: 'rgba(238, 43, 108, 0.16)',
    borderRadius: 18,
    borderWidth: 1,
    height: 50,
    justifyContent: 'center',
    width: 50,
  },
  editButtonText: {
    color: colors.primary,
    fontFamily: typography.fontFamily,
    fontSize: 22,
    fontWeight: '800',
    lineHeight: 24,
  },
  errorText: {
    color: colors.primary,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '700',
    marginTop: -4,
    textAlign: 'center',
  },
  formActions: {
    flexDirection: 'row',
    gap: 12,
  },
  formField: {
    gap: 8,
  },
  formInput: {
    backgroundColor: 'rgba(255, 204, 213, 0.16)',
    borderColor: 'rgba(255, 204, 213, 0.44)',
    borderRadius: 18,
    borderWidth: 1,
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 16,
    fontWeight: '800',
    minHeight: 60,
    paddingHorizontal: 18,
  },
  formLabel: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
    marginLeft: 6,
  },
  handle: {
    alignSelf: 'center',
    backgroundColor: 'rgba(238, 43, 108, 0.26)',
    borderRadius: 4,
    height: 7,
    marginBottom: 22,
    width: 76,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 8,
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  hello: {
    color: colors.primary,
    fontFamily: typography.fontFamily,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.6,
  },
  intro: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 1,
    gap: 12,
    minWidth: 0,
  },
  logoutArrow: {
    color: colors.white,
    fontFamily: typography.fontFamily,
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 20,
  },
  logoutButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(238, 43, 108, 0.08)',
    borderColor: 'rgba(238, 43, 108, 0.18)',
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    minHeight: 50,
    paddingLeft: 8,
    paddingRight: 14,
  },
  logoutIcon: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 14,
    height: 34,
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    width: 34,
  },
  logoutText: {
    color: colors.primary,
    fontFamily: typography.fontFamily,
    fontSize: 13,
    fontWeight: '800',
  },
  name: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 18,
    fontWeight: '800',
  },
  nameBlock: {
    flexShrink: 1,
    minWidth: 0,
  },
  saveButton: {
    alignItems: 'center',
    backgroundColor: colors.slate900,
    borderRadius: 18,
    flex: 1,
    paddingVertical: 17,
  },
  saveButtonText: {
    color: colors.white,
    fontFamily: typography.fontFamily,
    fontSize: 14,
    fontWeight: '800',
  },
  sheet: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 34,
    borderTopRightRadius: 34,
    gap: 18,
    paddingBottom: 36,
    paddingHorizontal: 24,
    paddingTop: 14,
  },
  sheetSubtitle: {
    color: colors.slate400,
    fontFamily: typography.fontFamily,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 20,
  },
  sheetTitle: {
    color: colors.slate900,
    fontFamily: typography.fontFamily,
    fontSize: 22,
    fontWeight: '800',
  },
});

export default styles;
